bicyclesscraping/urls.py
from django.contrib import admin
from django.urls import path
from scraping import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("signin/", views.signin, name="signin"),
    path("signout/", views.signout, name="signout"),
    path("create_bicycles/", views.scraping, name="create_bicycles"),
    path("extract_bicycles/", views.extract_bicycles_from_web, name="extract_bicycles"),
    path("search_bicycle/", views.search_bicycle, name="search_bicycle"),
    path("search_bicycle/<str:query>", views.search_bicycle, name="search_bicycle_filter"),
    path("price_history/<int:reference>", views.get_price_history, name="price_history"),
    path("subscription/", views.subscription, name="subscription"),
    path("unsubscription/", views.unsubscription, name="unsubscription"),
]

scraping/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Bicycle(models.Model):
    name=models.TextField(max_length=200)
    img=models.URLField(default="Image not available")
    current_price=models.FloatField()
    url=models.URLField()
    reference=models.IntegerField()

    def __str__(self):
        return self.name

class PriceHistory(models.Model):
    bicycle=models.ForeignKey(Bicycle, on_delete=models.CASCADE, related_name="price_history")
    date=models.DateField(default=timezone.now)
    price=models.FloatField()

    def __str__(self):
        return f"{self.date} : {self.price}"

class Subscription(models.Model):
    email=models.EmailField(max_length=60)
    reference=models.IntegerField(default=None)
    bicycle=models.ForeignKey(Bicycle, on_delete=models.CASCADE, related_name="subscription")

    def __str__(self):
        return self.email

scraping/forms.py
from django import forms
from .models import Bicycle, PriceHistory, Subscription

class BicycleForm(forms.ModelForm):
    class Meta:
        model = Bicycle
        fields = ["name", "img", "current_price", "url", "reference"]


class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ["email", "reference"]

scraping/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from bs4 import BeautifulSoup
import requests, os, dotenv
from urllib.parse import urljoin
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import plotly.graph_objects as go
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.db import IntegrityError
from .models import Bicycle, PriceHistory, Subscription
from .forms import SubscriptionForm
from .utils import create_bicycles
from django.http import JsonResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import threading
from django.contrib import messages

dotenv.load_dotenv()

url = "https://www.bikingpoint.es/es/"
bicycles_endpoint = "bicicletas.html"
search_endpoint = "catalogsearch/result/?q={}"
page_endpoint = "?p={}"
bicycles_url = urljoin(url, bicycles_endpoint)


def home(request):
    return render(request, "home.html")


def signup(request):
    if request.method == "GET":
        return render(request, "signup.html", {"form": UserCreationForm()})
    else:
        print(request.POST)
        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    username=request.POST["username"],
                    password=request.POST["password1"],
                )
                print(user)
                user.save()
                login(request, user)
                return redirect("home")
            except IntegrityError:
                return render(
                    request,
                    "signup.html",
                    {"form": UserCreationForm(), "error": "User already exists"},
                )
        else:
            return render(
                request,
                "signup.html",
                {"form": UserCreationForm(), "error": "Password not match"},
            )


def signin(request):
    form = AuthenticationForm(request)
    print(request)
    if request.method == "GET":
        return render(request, "signin.html", {"form": form})
    else:
        try:
            user = authenticate(
                request,
                username=request.POST["username"],
                password=request.POST["password"],
            )
            login(request, user)
            return redirect("home")
        except:
            return render(
                request,
                "signin.html",
                {"form": form, "error": "User or password incorrect."},
            )

@login_required
def signout(request):
    logout(request)
    return redirect("home")

def scraping(request):
    return render(request, "create_bicycles.html", {
        "cron_token": settings.CRON_SECRET_TOKEN
    })

def run_scraper(start_page, last_page):
    usp_warn = False
    counter = int(start_page)
    while not usp_warn and counter <= last_page:
        print(f"Get request page {counter}")
        response = requests.get(urljoin(bicycles_url, page_endpoint.format(counter)))
        if (
            "No podemos encontrar productos que coincida con la selección."
            in response.text
        ):
            usp_warn = True
            break
        # Creamos la soup con BeautifulSoup
        soup = BeautifulSoup(response.text, "html.parser")
        # Obtener el contenedor de cada bicicleta, crear cada Bycicle y guardar en una lista
        bicycles = soup.find_all("li", class_="item product product-item")
        counter += 1
        
        create_bicycles(bicycles)
    print("Scraping finished.")


@csrf_exempt
def extract_bicycles_from_web(request, start_page=1, last_page=30):
    print("Ejecutando extract_bicycles_from_web")
    if request.method != "POST":
        return JsonResponse({"error": "Only POST method"}, status=405)
    
    token = request.GET.get("token") or request.POST.get("token")
    if token != settings.CRON_SECRET_TOKEN:
        return JsonResponse({"error": "Not authorized"}, status=403)
    
    start_page = request.GET.get("start_page") or request.POST.get("start_page") or start_page
    last_page = request.GET.get("last_page") or request.POST.get("last_page") or last_page

    start_page = int(start_page)
    last_page = int(last_page)
    
    print(f"Scraping from page {start_page} to {last_page}")
    threading.Thread(target=run_scraper, args=(start_page, last_page)).start()

    if "text/html" in request.headers.get("Accept", ""):
        messages.success(request, "Scraping started in background")
        return redirect("create_bicycles")
    
    return JsonResponse({"message": "Scraping started in background"})



def search_bicycle(request, query=None):
    if request.method == "GET":
        return render(request, "search_bicycle.html")
    else:
        query = request.POST["query"]
        try:
            reference = int(query)
            if len(query) == 5:
                results = Bicycle.objects.filter(reference=reference)
            else:
                results = Bicycle.objects.filter(name__icontains=query)
        except:
            results = Bicycle.objects.filter(name__icontains=query)
        return render(request, "search_bicycle.html", {"results": results})


def get_price_history(request, reference):
    bicycle = get_list_or_404(Bicycle, reference=reference)[0]
    price_history_list = get_list_or_404(PriceHistory, bicycle=bicycle.pk)

    dates = sorted([price.date for price in price_history_list])
    prices = []
    for date in dates:
        price_history = PriceHistory.objects.filter(bicycle=bicycle.pk, date=date)[0]
        prices.append(price_history.price)

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=dates, y=prices, mode="lines+markers", name="Precio"))
    fig.update_layout(
        plot_bgcolor="#212529",
        paper_bgcolor="#212529",
        title={
            "text": f"{bicycle.name}",
            "x":0.5,
            "xanchor": "center",
            "font": {"size": 24, "family": "system-ui"}
        },
        xaxis=dict(
            title=dict(text="Date", font=dict(color="#f8f9fa")),
            color="#f8f9fa",
            gridcolor="#343a40",
            linecolor="#f8f9fa",
            tickfont=dict(color="#f8f9fa"),
        ),
        yaxis=dict(
            title=dict(text="Price (€)", font=dict(color="#f8f9fa")),
            color="#f8f9fa",
            gridcolor="#343a40",
            linecolor="#f8f9fa",
            tickfont=dict(color="#f8f9fa"),
        ),
        hovermode="x unified",
        font=dict(
            family="system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
            size=16,
            color= "#f8f9fa",
        ),
        margin=dict(t=100, b=40, l=40, r=20),
    )
    graphic = fig.to_html()

    return render(request, "price_history.html", {"graphic": graphic})

@login_required
def subscription(request):
    form = SubscriptionForm()
    if request.method == "GET":
        try:
            reference = request.GET.get("reference")
            form = SubscriptionForm(initial={"reference": reference})
            return render(request, "subscription.html", {
                "form": form,
                "reference": reference
            })
        except:
            return render(request, "subscription.html", {
                "form": form
            })
    else:
        bicycle = get_object_or_404(Bicycle, reference=request.POST["reference"])
        subscribe = Subscription(email=request.POST["email"], reference=request.POST["reference"], bicycle=bicycle)
        try:
            subs_object = get_object_or_404(Subscription, email = request.POST["email"], reference=request.POST["reference"])
            print(subs_object)
            return render(request, "subscription.html", {
                "form": form,
                "message": "Subscription already exist"
            })
        except:
            subscribe.save()
            return render(request, "subscription.html", {
                "form": form,
                "message": "Subscribed successfully!"
            })

@login_required
def unsubscription(request):
    form = SubscriptionForm()
    if request.method == "GET":
        return render(request, "unsubscription.html", {
            "form": form
        })
    else:
        subscription = get_object_or_404(Subscription, email=request.POST["email"], reference=request.POST["reference"])
        # try:
        subscription.delete()
        return render(request, "unsubscription.html", {
            "form": form,
            "message": f"Unsubscribeb from {subscription.bicycle}"
        })
        """
        except:
            return render(request, "unsubscription.html", {
                "form": form,
                "message": f"This subscription does not exist"
            })
        """



# system("clear")
# get_price_history(34687)





# Recibir la confirmacion de la suscripcion al mail
def send_subscript_confirm(email, reference):
    with open("subscription_list.json", "r") as file:
        file_json = json.load(file)
        new_user = True
        for user in file_json:
            if user["email"] == email:
                new_user = False
                if reference not in user["reference"]:
                    user["reference"].append(reference)
            print(user)
        if new_user:
            file_json.append({"email": email, "reference": [reference]})
        print(file_json)
        with open("subscription_list.json", "w") as file:
            json.dump(file_json, file, indent=4, ensure_ascii="utf-8")

    print("Subscribed")
    from_ = os.getenv("EMAIL")
    password = os.getenv("PASSWORD")

    mail = MIMEMultipart()
    mail["From"] = from_
    mail["To"] = email

scraping/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bike Price Tracker</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Bike Price Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'search_bicycle' %}">Search bicycles</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signout' %}">Sign out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'subscription' %}">Subscribe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'unsubscription' %}">Unsubscribe</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Sign up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signin' %}">Sign in</a>
                        </li>
                    {% endif %}
                    {% if user.username == "diegoayala" %}
                        <span class="navbar-text"><strong>Admin functions:</strong></span>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'create_bicycles' %}">Create bicycles</a>
                        </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                    <span class="navbar-text ms-auto">User: {{user.username}}</span>
                {% endif %}
            </div> 
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

scraping/templates/create_bicycles.html
{% extends "base.html" %}

{% block content %}
<main class="container py-3">
    <section class="card shadow-lg bg-dark text-light border-0 rounded-4">
        <div class="text-center mb-3">
            <h1 class="display-4 mb-3 text-accent fw-bold">Create Bicycles</h1>
            
            <form action="{% url 'extract_bicycles' %}" method="POST" class="d-flex flex-column align-items-center gap-3">
                {% csrf_token %}
                <input type="hidden" name="token" value="{{ cron_token }}">
                
                <div class="text-center d-flex mt-3 mb-3 w-100 justify-content-center">
                    <label class="text-end text-secondary fs-4 my-auto me-3 w-25" for="id_start_page">Start page</label>
                    <input class="form-control w-50 border-accent bg-dark my-auto text-light placeholder-light" type="number" name="start_page" id="id_start_page">
                </div>
                
                <div class="text-center d-flex mt-3 mb-3 w-100 justify-content-center">
                    <label class="text-end text-secondary fs-4 my-auto me-3 w-25" for="id_last_page">Last page</label>
                    <input class="form-control w-50 border-accent bg-dark my-auto text-light placeholder-light" type="number" name="last_page" id="id_last_page">
                </div>
                
                <div class="text-center py-3">
                    <button class="btn btn-accent btn-lg px-4 shadow-sm">Start</button>
                </div>
            </form>
            <div class="text-secondary fs-5">
                {{message}}
            </div>
            {% if messages %}
                <div class="text-secondary fs-5">
                    {% for message in messages %}
                        <div>
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

    </section>

</main>
{% endblock %}

scraping/templates/get_price_history.html
{% extends "base.html"%}

{% block content %}
<h1>Get Price History</h1>
<form action="" method="POST">
    <input type="text" name="" id="">
</form>
{% endblock %}

scraping/templates/home.html
{% extends "base.html" %}

{% block content %}
<main class="container py-5">
  <h1 class="display-4 text-center mb-5 fw-bold text-accent">Bike Price Tracker</h1>

  <section class="card shadow-lg rounded-4 border-0 p-4 bg-dark text-light">
    <div class="text-center mb-4">
      <h2 class="display-6 mb-3 text-accent">Search Bicycles</h2>
      <p class="text-secondary fs-5">Find a bicycle by name or reference</p>
    </div>

    <form class="d-flex flex-column align-items-center gap-3" action="search_bicycle/" method="POST">
      {% csrf_token %}
      <label class="text-secondary fs-4" for="">Name or Reference:</label>
      <input
        type="text"
        name="query"
        placeholder="Scott - 34687 - Team Race"
        class="form-control w-75 text-center fs-5 py-2 bg-dark border-accent text-light placeholder-light"
      />
      <button type="submit" class="btn btn-accent btn-lg px-5 shadow-sm">
        Search
      </button>
    </form>

    <hr class="my-4 border-secondary" />

    {% if not user.is_authenticated %}
    <div class="text-center">
      <p class="mb-3 fs-5 text-secondary">Sign in to get price alerts on bikes!</p>
      <div class="d-flex justify-content-center gap-3">
        <a href="/signin" class="btn btn-outline-light px-4 py-2">Sign In</a>
        <a href="/signup" class="btn btn-light px-4 py-2">Sign Up</a>
      </div>
    </div>
    {% endif %}
  </section>
</main>

{% endblock %}

scraping/templates/price_history.html
{% extends "base.html"%}

{% block content %}
<main class="container py-5">
    <section class="card shadow-lg rounded-4 border-0 p-4 bg-dark text-light">
        <div class="text-center mb-4">
            <h2 class="display-6 mb-3 text-accent">Get Price History</h2>
        </div>
        <div class="card card-body mt-5 bg-dark border-0 text-light" style="min-height: 500px;">
            <div class="w-100">
                {{graphic|safe}}
            </div>
        </div>
    </section>

</main>
{% endblock %}

scraping/templates/search_bicycle.html
{% extends "base.html" %}

{% block content %}
<main class="container py-3">
    <section class="card shadow-lg rounded-4 border-0 p-4 bg-dark text-light">
        <div class="text-center mb-3">
            <h2 class="display-4 mb-3 text-accent fw-bold">Search Bicycle</h2>
            <p class="text-secondary fs-5">Find a bicycle by name or reference</p>
        </div>

        <form class="d-flex flex-column align-items-center gap-3" action="" method="POST">
            {% csrf_token %}
            <label class="text-secondary fs-4" for="">Name or Reference:</label>
            <input class="form-control w-75 text-center fs-5 py-2 bg-dark border-accent text-light placeholder-light" type="text" name="query" placeholder="Scott - 34687 - Team Race">
            <div class="text-center py-3">
                <button class="btn btn-accent btn-lg px-5 shadow-sm">Search</button>
            </div>
        </form>
    </section>

    {% for result in results %}
    <section class="card shadow-lg rounded-4 border-0 p-4 bg-dark text-light my-3">
        <h2 class="text-accent fs-3 text-center mb-3">{{result.name}}</h2>
        <div class="row align-items-center g-4 ">
            <div class="col-md-4 text-center offset-md-1">
                <img class="img-fluid rounded-2 shadow-sm" src="{{result.img}}" alt="">
            </div>
            <div class="col-md-7 d-flex flex-column justify-content-center gap-3 ">
                <div>
                    <p class="fs-4 text-price fw-bold">{{result.current_price|floatformat:2}} € </p>
                    <p class="fs-4 text-secondary">Reference: {{result.reference}}</p>
                </div>
                <div class="d-flex flex-wrap gap-3">
                    <a href="{{result.url}}" class="btn btn-outline-light px-4">Visit site
                    </a>
                    <a href="{% url 'price_history' result.reference %}" name="price_history" class="btn btn-outline-light px-4">Price History

                    </a>
                    <a href="/subscription/?reference={{ result.reference }}" class="btn btn-outline-light px-4">Subscribe to price alerts
                    </a>

                </div>

            </div>
        </div>

    </section>
    {% endfor %}


</main>
{% endblock %}

scraping/templates/signin.html
{% extends "base.html" %}

{% block content %}
<main class="container py-3">
    <section class="card shadow-lg rounded-4 border-0 p-4 bg-dark text-light">
        <div class="text-center mb-3">
            <h2 class="display-4 mb-3 text-accent fw-bold">Sign in</h2>
            

            <form class="d-flex flex-column alig-item-center gap-3" action="" method="POST">
                {% csrf_token %}

                <div class="d-flex text-center mt-3 mb-3 w-100 justify-content-center">
                    <label class="text-end w-25 text-secondary fs-4 my-auto me-3" for="id_username">Username:</label>
                    <input class=" my-auto form-control w-50 fs-5 py-2 bg-dark border-accent text-light placeholder-light" type="text" name="username" id="id_username" autofocus placeholder=""  required  >
                </div>

                <div class="d-flex text-center mb-3 w-100 justify-content-center">
                    <label class="text-end w-25 text-secondary fs-4 my-auto me-3" for="id_password">Password:</label>
                    <input class=" my-auto form-control w-50  fs-5 py-2 bg-dark border-accent text-light placeholder-light" type="password" name="password" id="id_password" placeholder="" required  >
                </div>

                <div class="text-secondary fs-5">
                    {{error}}
                </div>

                <div class="text-center py-3">
                    <button class="btn btn-accent btn-lg px-5 shadow-sm">Sign in</button>
                </div>
            </form>

            <hr class="my-3 border-secondary">

            {% if not user.is_authenticated %}
            <div class="text-center">
                <p class="mb-3 fs-5 text-secondary">Don't have account?</p>
                <div class="d-flex justify-content-center gap-3">
                    <a href="/signin" class="btn btn-outline-light px-4 py-2">Sign In</a>
                    <a href="/signup" class="btn btn-light px-4 py-2">Sign Up</a>
                </div>
            </div>
            {% endif %}

        </div>

    </section>
</main>
{% endblock %}

scraping/templates/signup.html
{% extends "base.html" %}

{% block content %}
<main class="container py-3">
    <section class="card shadow-lg rounded-4 border-0 p-4 bg-dark text-light">
        <div class="text-center mb-3 ">
            <h2 class="display-4 text-accent fw-bold mb-3">Sign up</h2>
        </div>

        <form class="d-flex flex-column align-items-center gap-3" action="/signup/" method="POST">
            {% csrf_token %}
            

            <div class="d-flex w-100 text-center my-3 justify-content-center">
                <label class="text-end w-25 text-secondary fs-4 my-auto me-3" for="id_username">Username:</label>
                <input class="bg-dark w-50 my-auto form-control fs-5 border-accent text-light placeholder-light" type="text" name="username" id="id_username" placeholder="" autofocus required>
            </div>
            
            <div class="d-flex w-100 text-center mb-3 justify-content-center">
                <label class="text-end w-25 text-secondary fs-4 my-auto me-3" for="id_password1">Password:</label>
                <input class="bg-dark w-50 my-auto form-control fs-5 border-accent text-light placeholder-light" type="password" name="password1" id="id_password1" placeholder="" autofocus required>
            </div>
            
            <div class="d-flex w-100 text-center mb-3 justify-content-center">
                <label class="text-end w-25 text-secondary fs-4 my-auto me-3" for="id_password2">Repeat password:</label>
                <input class="bg-dark w-50 my-auto form-control fs-5 border-accent text-light placeholder-light" type="password" name="password2" id="id_password2" placeholder="" autofocus required>
            </div>
            
            <div class="text-secondary fs-5">
                {{error}}
            </div>

            <div class="text-center py-3">
                <button class="btn btn-accent btn-lg px-5 shadow-sm">Sign Up</button>
            </div>


        </form>

    </section>
</main>
{% endblock %}

scraping/templates/subscription.html
{% extends "base.html" %}

{% block content %}
<main class="container py-3">
    <section class="card shadow-lg rounded-4 border-0 p-4 bg-dark text-light">
        <div class="text-center mb-3">
            <h2 class="display-4 mb-3 text-accent fw-bold">Subscription</h2>
            <p class="text-secondary fs-5">Receive alerts when the price change.</p>
            
            <form class="d-flex flex-column align-items-center gap-3" action="" method="POST">
                {% csrf_token %}
                    
                <div class="d-flex text-center mt-3 mb-3 w-100 justify-content-center">
                    <label class="text-end text-secondary fs-4 my-auto me-3 w-25" for="id_email">Email:</label>
                    <input class="form-control w-50 border-accent bg-dark my-auto text-light placeholder-light" type="email" name="email" id="id_email" placeholder="">
                </div>
                
                <div class="d-flex text-center mb-3 w-100 justify-content-center">
                    <label class="text-end text-secondary fs-4 my-auto me-3 w-25" for="id_reference">Reference:</label>
                    <input class="form-control w-50 border-accent bg-dark my-auto text-light placeholder-light" type="number" name="reference" id="id_reference" placeholder="" value="{{ reference }}">
                </div>
                
                <div class="text-center">
                    <p class="text-secondary fs-4">{{message}}</p>
                </div>

                <div class="text-center py3">
                    <button class="btn btn-lg btn-accent px-5 shadow-sm">Subscribe</button>
                </div>
            </form>
        </div>

    </section>
</main>
{% endblock %}

scraping/templates/unsubscription.html
{% extends "base.html" %}

{% block content %}
<main class="container py-3">
    <section class="card border-0 rounded-4 shadow-lg bg-dark text-light p-4">
        <div class="text-center mb-3">
            <h2 class="display-4 mb-3 text-accent fw-bold">Unsubscription</h2>
            
            <form class="d-flex flex-column align-items-center gap-3" action="">
                {% csrf_token %}

                <div class="text-center d-flex mt-3 mb-3 w-100 justify-content-center">
                    <label class="text-end text-secondary fs-4 my-auto me-3 w-25" for="id_email">Email:</label>
                    <input class="form-control w-50 border-accent bg-dark my-auto text-light placeholder-light" type="email" name="email" id="id_email" placeholder="">
                </div>

                <div class="d-flex text-center mb-3 w-100 justify-content-center">
                    <label class="text-end text-secondary fs-4 my-auto me-3 w-25" for="id_reference">Reference:</label>
                    <input class="form-control w-50 border-accent bg-dark my-auto text-light placeholder-light" type="number" name="reference" id="id_reference" placeholder="">
                </div>

                <div class="text-center">
                    <p class="text-secondary fs-4">{{message}}</p>
                </div>

                <div class="text-center py3">
                    <button class="btn btn-lg btn-accent px-5 shadow-sm">Unsubscribe</button>
                </div>
            </form>
        </div>
    </section>

</main>
{% endblock %}